# Generated by Django 5.0 on 2023-12-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='teste',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
