# Generated by Django 5.0 on 2023-12-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='teste',
        ),
    ]
