# Generated by Django 5.0 on 2023-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tag_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
